### ISSUE TITLE
Regression: Subdomain Drops off in 1.0.X Branch

### ISSUE THREAD

**Issue by JoeCianflone** [tighten/ziggy#383]
#### Description

Using ziggy 1.0.X (I tested this in .0 - .3) a url that is supposed to have a subdomain does not. 

**If I revert back to 0.9.4 the subdomain issues goes away**

#### Expected behavior

`route('foo') // should return foo.mysite.com`

is actually return

`route('foo') // actually returns mysite.com`

#### Environment

- **Laravel version**:  Latest 8
- **Ziggy version**: 1.0.0 - 1.0.3

**Related routes**:

All routes with a subdomain seem to have an issue. I'm not using the Spatie multi-tenant package, however, I am routing via middleware to my tenants and NOT using laravel's `domain` method in my route calls

```php
Route::get('login', Login::class)->name('login');
```

**`Ziggy.routes`**:

I use `@routes` I can copy and paste the output if you need it, but it's a lot so just let me know and I can do that, I didn't want to just dump it all in here...

**Comment by bakerkretzmar** [comment]
What does `{{ route('foo') }}` (the Laravel helper) in one of your Blade views output?

**Comment by JoeCianflone** [comment]
Huh so this is strange...I don't use the route helper in blade because I use InertiaJS and Vue. So I use use the `mixin` So for a real route called logout:

```php
Route::get('logout', ProcessLogout::class)->name('logout');
```

### From the console:

in 1.0.3 I get

```
https://rebase.test/logout
```

in 0.9.4 I get:

```
https://joecianflone.rebase.test/logout
```

but from the route I get the correct subdomain in 1.0.3 and 0.9.4

**Comment by bakerkretzmar** [comment]
What do you mean "from the route" you get the correct subdomain? Can you `tinker` and call `route('logout')` in PHP and share what it outputs?

This is happening because we switched from using `url('/')` (which comes from the request) to `APP_URL`. You're not the first person to run into this issue so we clearly need a better escape hatch 🙃 just want to make sure nothing else is wrong too.

**Comment by bakerkretzmar** [comment]
What do you mean "from the route" you get the correct subdomain? Can you `tinker` and call `route('logout')` in PHP and share what it outputs?

This is happening because we switched from using `url('/')` (which comes from the request) to `APP_URL`. You're not the first person to run into this issue so we clearly need a better escape hatch 🙃 just want to make sure nothing else is wrong too.

**Comment by JoeCianflone** [comment]
Sorry! "from the route" I meant to says, "from blade" 

**in 1.0.3:**
From `route('logout)` in blade I'd get `https://foo.rebase.test/logout` -- which is correct

From `route('logout')` in a Vue component I'd get `https://rebase.test.logout` -- which is incorrect

let me know if you need anything else
