### ISSUE TITLE
XSRF token missing

### ISSUE THREAD

**Issue by yormy** [tighten/ziggy#413]
Lost...
When I use the ziggy route to generate the url I get a 419 (CSRF token missing), and when I use the fully qualified same url directly into the axios call, i do not this error

In the request headers in both situations I see the cookies and in the cookie the XSRF-TOKEN is set,
but in the case of the 419, the XSRF-token is not translated into x-xsrf-token: in the header, hence the 419

When I add the x-xsrf-token header manualy in the axios request interceptor then the call works fine, but I guess that should not have to be the case.

Any ideas ?

`      const url = this.route('users.logs.delete');
      this.axios
        .delete(url) //  419
`

`
      this.axios
        .delete(https://example.com/users/log/delete) //  no 419

`

**Comment by yormy** [comment]
Update:
const url = this.route('users.logs.delete').url();
then it works again

**Comment by bakerkretzmar** [comment]
This is because Ziggy v0.9 returns a JavaScript `String` object, which axios does not consider to be strictly equal to the actual URL for security reasons.

In Ziggy v0.9 and earlier, the fix is the solution you found: calling `.url()` explicitly.

Ziggy v1 returns a plain string, so updating would also fix this for you.

**Comment by yormy** [comment]
Thanks... just figured that out after the .url() and seeing the commits.
I can confirm that by upgrading to 1.05 everything works again
Thanks for the awesome package (and incredibly speedy response)
