### ISSUE TITLE
How can I put the default route in the beginning of the route ?

### ISSUE THREAD

**Issue by jeanali** [tighten/ziggy#418]
Is there any way to put default to the route?

Like have this structure  ```route('stores.products.index');``` in my route  & I need to make the ```stores``` defult in the route and being like this  ``` route('products.index');```  without each time put  ```stores``` each time! 

I'm using this pacakge with ```inertiajs```

**Comment by bakerkretzmar** [comment]
Yes this is possible, you would set it up in your Laravel app. It's in the docs under [URL Generation > Default Parameters](https://laravel.com/docs/8.x/urls#default-values).

Basically, in a middleware or service provider, call `URL::defaults(['stores' => 'your-default-value']);`. Note that this will affect **all** route parameters called `stores`, in all routes.

Closing because this isn't directly a Ziggy concern, but feel free to reply again if you have any other questions!
