### ISSUE TITLE
Feature Request:  Setting for a fallback route

### ISSUE THREAD

**Issue by mhelaiwa** [tighten/ziggy#560]
# Description

Ziggy will through an exception if the route-name does not exist in the route list. This will cuase a problem if we have route names coming from staging DB to build a sidebar menu.
All team members who don't have the routes in their copy of the project will have exceptions.

# Suggestion

Set a global default `Not found route` in the configuration say `404` or whatever. this way no exception will occur.
The suggested solution could be to set a fallback route inside `ziggy.php` config file:
```
<?php
return [
    'except' => [...],
    // route name or url
    'fallback-route-name' => 'route-404',
];
```

# Alternatives

Currently I am solved this problem in vuejs through intermediate function inside vue mixins. but it would be nice to have this feature by default into Ziggy:

```
// vue-mixins

import Vue from 'vue';

Vue.mixin({
    methods: {
        r(name,params,absolute,config){
            try{
                return this.route(name,params,absolute,config);
            }catch (e) {
                return '404';
            }
        },
    }
});

```

```
// vue component
// use r( ... ) instead of route( ... )
<templet>
        <router-link  :to="r('dashboard')">Dashboard</router-link>
</templet>
```

**Comment by bakerkretzmar** [comment]
Your route _names_ are coming from the database? How does that work exactly?

What does Laravel's `route()` helper do in this situation if you call it on a route that doesn't exist?

Ziggy does have a method to check if a route exists, so your route wrapper could be simplified a bit to something like this:

```js
Vue.mixin({
    methods: {
        r(name, params, absolute, config) => this.route().has(name) ? this.route(name, params, absolute, config) : '404',
    }
});
```

This has the added benefit of not silencing _all_ Ziggy errors.

**Comment by mhelaiwa** [comment]
@bakerkretzmar 
1- Our system contains a navigation menu and many people work on the same project.
2- So each devloper work on a specific module which has it's own link in the menu.
3- Each menu link in DB contains (id - title - route name).
4- Suppose that your colleague worked on his module and created its menu link and corresponding routes. The menu will be rendered for each developer connected to the same DB but those how don't have the routes in their version will have errors.

So I think in this situation default route will help.
Anyways thanks for the simplificaion. :)

**Comment by bakerkretzmar** [comment]
Okay, and what does Laravel's `route()` helper do here?

I'm pretty sure this isn't something we'll solve inside Ziggy itself, in general the current behaviour is exactly what we want—an error if you try to use a route that doesn't exist.

I'm not familiar with your app of course, but this also feels to me like something that should be solved at a higher level than Ziggy or inside your components. For example you could avoid showing menu items for modules that don't exist, or you could set up some dynamic 'page' routes that accept parameters dependent on the database, instead of making the routes themselves depend on it.

**Comment by mhelaiwa** [comment]
@bakerkretzmar 
All of this is handled by vuejs not by laravel. I am OK that you can handle it by several ways but it would be nice if we have a route function with a default route.

**Comment by bakerkretzmar** [comment]
Yep, just wondering because Laravel's route helper is the functionality we're trying to match. In Laravel if you try to call `route()` on a route that doesn't exist, it throws an exception, which is what Ziggy does too and which I think makes sense.

In your particular case I think the workaround above is the right approach, rather than including this in Ziggy itself. Gonna close this but let me know if you have any other questions.
