### ISSUE TITLE
Completely unable to get route() working in Vue 3 with TypeScript

### ISSUE THREAD

**Issue by Healyhatman** [tighten/ziggy#578]
### Ziggy version

1.4.6

### Laravel version

8.83

### Description

I am trying to get route() to working in my Vue 3 / Mix / Typescript project and it's been a few hours now of no progress.

I am importing the files into app.ts directly (without an alias) and have included use(ZiggyVue, Ziggy).

The absolutely infuriating thing is that an error is thrown in the child Vue component, but NOT the parent which ALSO USES route() !

The route() call in the parent component works fine and returns the correct route, but attempting npm run dev throws an error

 ERROR in C;\....\ChildComponent.vue.ts TS2304: Cannot find name 'route'.

### Ziggy call and context

```js
In ChildComponent.vue


<script setup lang="ts">

const saveCase = async() => {
    saving.value = true;
    try {
        let response = await axios.post(route('admin.dex.cases.store'), dexCase.value);
    } catch(e) {
        console.log(e);
    }
    saving.value = false;
}
```

### Ziggy configuration

```js
footer.blade : 

@routes

<!-- bunch of stuff -->
<script src="{{ mix('/js/app.js') }}"></script>
=====================================================


console.log(Ziggy) : 

url: "https://localhost:543"
routes: { ...., admin.dex.cases.store: {uri: 'admin/dex/cases', methods: Array(1)} }
=====================================================

app.ts :

import { createApp } from "vue";
const app = createApp({});

//@ts-ignore
import { ZiggyVue } from "../../../vendor/tightenco/ziggy/src/js/vue";
//@ts-ignore
import { Ziggy } from "../../../vendor/tightenco/ziggy/dist";

app
    .use(ZiggyVue, Ziggy)

====================================================
```

### Route definition

```php
These are grouped routes and they work jsut fine if I call them in the javascript console.
```

**Comment by bakerkretzmar** [comment]
There are a few things going on here 😅 

- You're not installing the plugin properly—the first argument to `.use()` needs to be the plugin itself, and the second is a configuration object for the plugin. You're passing the plugin source file as the first argument and then the plugin again as the second argument too. Import the plugin like this: `import { ZiggyVue } from '../../../vendor/tightenco/ziggy/dist/vue'` (from `dist`, not `src`). The second argument should be your routes, which you need to generate and save to a file using the `php artisan ziggy:generate` command. Then, import them with something like `import { Ziggy } from './ziggy.js'`.
- After installing the plugin, `route` is available as a mixin and `provide`d to all your components. In your component's `<script>` tags, using the Options API (Vue 2) you can access it with `this.route`, but using the Composition API (Vue 3) there isn't a `this` usually, so in every component where you want to use it you need to either import the function again manually or inject it with `const route = inject('route')`. This does _not_ apply to the `<template>` part of your components, `route` will work fine there throughout the whole app.
- `route` works in your browser console because you're also using the `@routes` Blade directive, effectively installing Ziggy twice. If you install the Vue plugin and generate your routes with `php artisan ziggy:generate`, you don't need to include the `@routes` Blade directive. Alternatively, you may be able to use the Blade directive alone and not install the Vue plugin at all, but that might depend on your setup and TypeScript won't like it.
- I think the code you showed actually works, is TypeScript complaining but it still actually runs fine, or is it broken? Even though your Vue plugin wouldn't be working, because you used `@routes` in your Blade template the `route` function actually should be available in your child component because it's available globally, although TypeScript wouldn't know that.

I'm going to close this because it doesn't appear to be a bug in Ziggy but if you have any other questions feel free to reply and I can try to help.

**Comment by Healyhatman** [comment]
Thanks for the detailed reply. It's tough when you're trying to smoosh 2 new languages/frameworks in your brain at once!

I don't want to use ziggy:generate because only parts of the application are in Vue / ES6. A lot of it is still in jQuery, back from version 1.6, so I need the routes in the blade. Also I will 100% forget to generate the routes at some point, update 150 clients, and they'll all be broken :D

**Comment by bakerkretzmar** [comment]
No worries! If you have to keep `@routes` in your Blade template anyway, I'm pretty sure you could get away with not installing the Vue plugin at all. The `route` function would be available globally, you'd just have to figure out how to tell TypeScript that (or make it ignore it).

**Comment by Healyhatman** [comment]
I've been telling it to `import route from "@ziggy/dist";` and that seems to shut it up
