### ISSUE TITLE
Add new command line options to generate the routes script

### ISSUE THREAD

**Issue by MuriloChianfa** [tighten/ziggy#599]
#### Description

Todays at ziggy:generate command, the output format only is defined by [config file](https://github.com/tighten/ziggy/blob/083b19fe137092732436427ab3515df1e1c6fbc1/src/CommandRouteGenerator.php#L52), the ideia is change this with some command lines arguments.

#### Suggestion

Add new command line options to generage command, as a "--script", "--merge-script"

#### Alternatives

Runs command with not required args, example:

$ php artisan ziggy:generate --file
$ php artisan ziggy:generate --script
$ php artisan ziggy:generate --merge-script

or 

$ php artisan ziggy:generate --output=file
$ php artisan ziggy:generate --output=script
$ php artisan ziggy:generate --output=merge-script

**Comment by MuriloChianfa** [comment]
Dont forget to add this in readme, because i had to read the code to discover how change the output format hahahaha LMAO.

**Comment by bakerkretzmar** [comment]
Thanks! The `ziggy:generate` command only outputs the 'file' format, so you couldn't use 'script' or 'merge-script' with it because those formats are generated by the Blade directive and get inserted into your views, they're never output to a file (and it wouldn't make sense to). A command line argument to specify a formatter class for the 'file' format would be possible, but that seems harder to me than setting the config value and it makes the command much longer.
