### ISSUE TITLE
Alternative route definition syntax yields @routes blade directive error

### ISSUE THREAD

**Issue by theojlab** [tighten/ziggy#618]
### Ziggy version

1.5

### Laravel version

9.49

### Description

The following route syntax in routes/web.php which is otherwise acceptable to Laravel framework (i.e. works fine if I remove @routes from blade template)
 
Route::match(['GET', 'POST'], '/login', [
    'as' => 'login',
    'uses' => [AuthController::class, 'login'],
]);

causes the error 

"[ReflectionFunction::__construct(): Argument #1 ($function) must be of type Closure|string, array given"

when processing @routes() in a blade template.

I am able to work around the issue by changing the way I specify the routes in web.php to instead write

Route::match(['GET', 'POST'], '/login', [AuthController::class, 'login'])->name('login');

and then I can use @routes() without problem.

![image](https://user-images.githubusercontent.com/18117435/216073796-263b5e9a-fc23-4429-8791-aca0e7a10185.png)

### Ziggy call and context

```js
@section('content_header')
    @routes()
@stop
```

### Ziggy configuration

```js
Server-side error
```

### Route definition

```php
// Syntax that produces error
Route::match(['GET', 'POST'], '/login', [
    'as' => 'login',
    'uses' => [AuthController::class, 'login'],
]);

// Alternative that does not
Route::match(['GET', 'POST'], '/login', [AuthController::class, 'login'])->name('login');
```

**Comment by bakerkretzmar** [comment]
Thanks for the detailed description of your issue! This:

```php
Route::match(['GET', 'POST'], '/login', [
    'as' => 'login',
    'uses' => [AuthController::class, 'login'],
]);
```

is actually not a valid route definition and will break in other places too, not just with Ziggy. If you run `php artisan route:list` there is no action listed for that route, and in a test if you just try to do `$this->get('/login')->assertOk()` you should get the same error that you're seeing above with `@routes`.

Laravel only supports the special callable `[Controller::class, 'method']` syntax if you're using 'fluent' routing. The key bit of code here is inside [`Illuminate\Routing\RouteAction::parse()`](https://github.com/laravel/framework/blob/9.x/src/Illuminate/Routing/RouteAction.php#L32)—it checks if the **entire route action** is callable before parsing it into a `ControllerName@method` string.

`[AuthController::class, 'login']` is callable, and so that works if it's the entire route action, but `['as' => 'login', 'uses' => [AuthController::class, 'login']]` is not callable, and so it won't be parsed correctly, leading to your actual route handler being literally `['as' => 'login', 'uses' => [AuthController::class, 'login']]`, which causes the error you're seeing.

As you mentioned, this would work instead:

```php
Route::match(['GET', 'POST'], '/login', [AuthController::class, 'login'])->name('login');
```

Or, so would this (assuming you have the necessary namespace set up in your RouteServiceProvider):

```php
Route::match(['GET', 'POST'], '/login', [
    'as' => 'login',
    'uses' => 'AuthController@login',
]);
```

Let me know if you have any other questions!
