### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by fatrex** [tighten/ziggy#730]
#### Description
Hi! 
I have the need to migrate a project from Laravel 10 to 11. I have followd the upgrade guide, upgraded all the upgradable packages but when I start the application I get some errore related to Ziggy. I think it's something related to new Laravel 11 classes.

#### Suggestion

Support to Laravel 11.

Many thanks!

**Comment by bakerkretzmar** [comment]
Ziggy already supports Laravel 11. If you can share the full details of the error you're seeing and your setup, including the code, I'd be happy to take a look. Feel free to reply here and if it's a bug we can re-open this.

**Comment by OmarBouziane** [comment]
Class "Tightenco\Ziggy\Ziggy" Not Found After Upgrading to Laravel 11

Hello,

I recently attempted to upgrade my application to Laravel 11 and encountered a significant issue. Specifically, the "Tightenco\Ziggy\Ziggy" class could not be found, causing my application to break. This issue arises in the context of an application that utilizes Laravel with Inertia.js and Vue.js.

Here is my configuration:

In the HandleInertiaRequests middleware, I'm attempting to use the Ziggy class as follows:

```
use Tightenco\Ziggy\Ziggy;

'ziggy' => function () use ($request) {
    return array_merge((new Ziggy)->toArray(), [
        'location' => $request->url(),
    ]);
},

```
In app.js, I import ZiggyVue for use with Vue.js:

```
import { ZiggyVue } from '../../vendor/tightenco/ziggy/dist/vue.m';

// Usage with Vue
.use(ZiggyVue)

```
In app.blade.php, I include the routes with @routes.

Here are the relevant versions of the tools and libraries I'm using:

    Laravel: 11.06
    Vue.js: 3.4.21
    inertiajs/inertia-laravel: 1.0.0
     inertiajs/vue3: 1.0.15

Has anyone else encountered this issue, or does anyone have suggestions on how to resolve it? Any assistance would be greatly appreciated as I am currently unable to proceed with the Laravel 11 upgrade due to this problem.

Thank you!

**Comment by fatrex** [comment]
Ah great! I'll retry the migration then and check deeply if is something on my side or if I found a bug!
Thanks!

**Comment by rajan-parmar** [comment]
@bakerkretzmar 
I am getting below error message:
- tightenco/ziggy v2.3.0 requires laravel/framework >=9.0 -> satisfiable by laravel/framework[v11.0.0, ..., v11.25.0].
